# Generated by Django 6.0.7 on 2026-08-12 05:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HevyLiftAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        help_text="Exercise name as Hevy emits it in its CSV export.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "to_name",
                    models.CharField(
                        help_text="Canonical lift name used by the strength standards.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Hevy lift aliases",
                "db_table": "hevy_liftalias",
                "ordering": ["from_name"],
            },
        ),
    ]
