# Generated by Django 6.0.8 on 2026-08-18 03:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_imports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrongLiftAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        help_text="Exercise name as Strong emits it in its CSV export.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "to_name",
                    models.CharField(
                        help_text="Canonical lift name used by the strength standards.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Strong lift aliases",
                "db_table": "strong_liftalias",
                "ordering": ["from_name"],
            },
        ),
    ]
