# Generated by Django 6.0.8 on 2026-08-25 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workout_imports", "0002_strongliftalias"),
        # Must run after the unified core.LiftAlias table has this app's
        # rows copied into it, or the delete loses data.
        ("core", "0004_copy_legacy_lift_aliases"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HevyLiftAlias",
        ),
        migrations.DeleteModel(
            name="StrongLiftAlias",
        ),
    ]
