# Generated by Django 6.0.7 on 2026-07-30 22:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "is_liftosaur_builtin",
                    models.BooleanField(
                        default=False,
                        help_text="Liftosaur ships this exercise natively; no custom exercise needs to be provisioned in the user's Liftosaur account.",
                    ),
                ),
                (
                    "is_bodyweight_added",
                    models.BooleanField(
                        default=False,
                        help_text="The strength standard threshold for this lift already includes the lifter's bodyweight; the recorded weight is the added weight on top of bodyweight (e.g. Pull-up, Chin-up, Dip).",
                    ),
                ),
            ],
            options={
                "db_table": "liftosaur_lift",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LiftAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        help_text="Exercise name as Liftosaur emits it in history payloads.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "to_name",
                    models.CharField(
                        help_text="Canonical lift name used by the strength standards.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lift aliases",
                "db_table": "liftosaur_liftalias",
                "ordering": ["from_name"],
            },
        ),
        migrations.CreateModel(
            name="LiftosaurSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(null=True)),
                ("result_summary", models.TextField(blank=True)),
                ("error_detail", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liftosaur_sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "liftosaur_synclog",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LiftHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lift", models.CharField(max_length=100)),
                ("performed_at", models.DateField()),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=7)),
                ("reps", models.PositiveIntegerField()),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Equipment/variant suffix from the Liftosaur history line (e.g. 'Leverage Machine'); empty when the set named no equipment. Distinguishes assisted-machine sets, whose recorded weight is already the net total load, from free bodyweight or added-weight sets of the same lift.",
                        max_length=100,
                    ),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lift_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "liftosaur_lifthistory",
                "ordering": ["-performed_at"],
                "unique_together": {
                    ("user", "lift", "performed_at", "reps", "weight_kg")
                },
            },
        ),
    ]
