# Generated by Django 6.0.7 on 2026-08-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liftosaur", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lifthistory",
            name="source",
            field=models.CharField(
                choices=[("liftosaur", "Liftosaur"), ("manual", "Manual")],
                default="liftosaur",
                help_text="Where this set came from: a Liftosaur sync pull, or a lifter self-reporting a completed set with no tracker connected.",
                max_length=20,
            ),
        ),
    ]
