# Generated by Django 6.0.8 on 2026-08-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liftosaur", "0005_alter_lifthistory_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifthistory",
            name="source",
            field=models.CharField(
                choices=[
                    ("liftosaur", "Liftosaur"),
                    ("manual", "Manual"),
                    ("hevy", "Hevy"),
                    ("strong", "Strong"),
                    ("wger", "Wger"),
                    ("hevy_api", "Hevy (live sync)"),
                ],
                default="liftosaur",
                help_text="Where this set came from: a Liftosaur sync pull, or a lifter self-reporting a completed set with no tracker connected.",
                max_length=20,
            ),
        ),
    ]
