# Generated by Django 6.0.8 on 2026-08-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liftosaur", "0007_delete_liftalias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifthistory",
            name="source",
            field=models.CharField(
                choices=[
                    ("liftosaur", "Liftosaur"),
                    ("liftosaur_csv", "Liftosaur (CSV import)"),
                    ("manual", "Manual"),
                    ("hevy", "Hevy"),
                    ("hevy_csv", "Hevy (CSV import)"),
                    ("wger", "Wger"),
                    ("strong", "Strong (CSV import)"),
                ],
                default="liftosaur",
                help_text="Where this set came from: a Liftosaur sync pull, or a lifter self-reporting a completed set with no tracker connected.",
                max_length=20,
            ),
        ),
    ]
