# Generated by Django 6.0.8 on 2026-08-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="very_open_invite_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Join link for the current year's Very Open. Blank hides the onboarding invite step entirely -- clear this once the invite window closes rather than leaving a dead link live.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="very_open_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Displayed name for the current year's Very Open, e.g. \"The Very Open '26\". Only shown when the invite URL above is also set.",
                max_length=100,
            ),
        ),
    ]
