# Generated by Django 6.0.8 on 2026-08-25 22:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_sitesettings_very_open_invite_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiftAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("liftosaur", "Liftosaur"),
                            ("hevy", "Hevy"),
                            ("strong", "Strong"),
                            ("wger", "Wger"),
                        ],
                        help_text="Which tracker's raw exercise-name vocabulary this alias translates from.",
                        max_length=20,
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        help_text="Exercise name as this tracker emits it.",
                        max_length=100,
                    ),
                ),
                (
                    "to_name",
                    models.CharField(
                        help_text="Canonical lift name used by the strength standards.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lift aliases",
                "db_table": "core_liftalias",
                "ordering": ["source", "from_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "from_name"),
                        name="core_liftalias_unique_source_from_name",
                    )
                ],
            },
        ),
    ]
