# Generated by Django 6.0.8 on 2026-08-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_copy_legacy_lift_aliases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liftalias",
            name="source",
            field=models.CharField(
                choices=[
                    ("liftosaur", "Liftosaur"),
                    ("hevy", "Hevy"),
                    ("strong", "Strong"),
                    ("wger", "Wger"),
                    ("fitnessvolt", "FitnessVolt"),
                ],
                help_text="Which tracker's raw exercise-name vocabulary this alias translates from.",
                max_length=20,
            ),
        ),
    ]
