# Generated by Django 6.0.8 on 2026-08-27 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_copy_fitnessvolt_lift_aliases"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportedApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "is_affiliate",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a commercial relationship (e.g. an affiliate coupon) exists, requiring the disclosure to render.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "supported app",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupportedAppMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("live_sync", "live sync"),
                            ("csv_upload", "csv upload"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "supported_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modes",
                        to="core.supportedapp",
                    ),
                ),
            ],
            options={
                "ordering": ["mode"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supported_app", "mode"),
                        name="core_supportedappmode_unique_app_mode",
                    )
                ],
            },
        ),
    ]
