# Generated by Django 6.0.8 on 2026-08-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_seed_supported_apps"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportedapp",
            name="coupon_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Affiliate coupon code for this app, if any (e.g. Liftosaur's VERYLIFT). Blank means no code renders on this app's card.",
                max_length=50,
            ),
        ),
    ]
