# Generated by Django 6.0.8 on 2026-08-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hevy_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hevysynclog",
            name="since_used",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="hevysynclog",
            name="walk_complete",
            field=models.BooleanField(default=True),
        ),
    ]
