# Generated by Django 6.0.7 on 2026-08-04 04:51

import uuid

from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("display_name", models.CharField(blank=True, max_length=150)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "oidc_sub",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "liftosaur_api_key",
                    core.fields.EncryptedCharField(
                        blank=True, max_length=600, null=True
                    ),
                ),
                (
                    "unit_preference",
                    models.CharField(
                        choices=[("kg", "Kilograms (kg)"), ("lb", "Pounds (lb)")],
                        default="kg",
                        max_length=2,
                    ),
                ),
                (
                    "acquisition_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Unknown"),
                            ("invite_link", "Challenge invite link"),
                            ("direct", "Direct signup"),
                            ("oidc", "Single sign-on"),
                            ("admin", "Created by an operator"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(blank=True, default="", max_length=10)),
                ("timezone", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("tos_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user",
            },
        ),
    ]
