# Generated by Django 6.0.7 on 2026-08-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_ratelimit_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="detected_timezone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
