# Generated by Django 6.0.7 on 2026-08-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_detected_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="unit_preference",
            field=models.CharField(
                choices=[("kg", "Kilograms (kg)"), ("lb", "Pounds (lb)")],
                default="lb",
                max_length=2,
            ),
        ),
    ]
