# Generated by Django 6.0.8 on 2026-08-18 03:53

from django.db import migrations

import core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_unit_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hevy_api_key",
            field=core.fields.EncryptedCharField(blank=True, max_length=600, null=True),
        ),
    ]
