# Generated by Django 6.0.8 on 2026-08-18 03:48

from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_unit_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wger_api_token",
            field=core.fields.EncryptedCharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wger_instance_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
