# Generated by Django 6.0.8 on 2026-08-18 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_hevy_api_key"),
        ("accounts", "0005_wger_integration"),
    ]

    operations = []
