# Generated by Django 6.0.8 on 2026-08-27 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_hevy_api_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tos_accepted_at",
        ),
    ]
