# Generated by Django 6.0.8 on 2026-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_remove_user_tos_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bodyweight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bodyweight_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Entered manually"),
                    ("tracker", "Synced from a connected tracker"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bodyweight_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
