# Generated by Django 6.0.8 on 2026-08-18 03:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WgerLiftAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        help_text="Exercise name as Wger's exerciseinfo endpoint returns it.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "to_name",
                    models.CharField(
                        help_text="Canonical lift name used by the strength standards.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lift aliases",
                "db_table": "wger_liftalias",
                "ordering": ["from_name"],
            },
        ),
        migrations.CreateModel(
            name="WgerSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(null=True)),
                ("result_summary", models.TextField(blank=True)),
                ("error_detail", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wger_sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wger_synclog",
                "ordering": ["-started_at"],
            },
        ),
    ]
