# Generated by Django 6.0.7 on 2026-08-04 04:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("challenges", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PointEarnEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lift", models.CharField(max_length=100)),
                ("performed_at", models.DateField()),
                ("synced_at", models.DateTimeField()),
                ("reps", models.PositiveIntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=7)),
                ("points_earned", models.PositiveIntegerField()),
                ("is_current_best", models.BooleanField()),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Equipment/variant suffix of the source LiftHistory set (e.g. 'Leverage Machine'); empty when the set named no equipment. Part of the re-scoring idempotency key so a bodyweight set and an assisted set of the same lift on the same day with the same rep count are never collapsed into one event.",
                        max_length=100,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="point_earn_events",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="point_earn_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scoring_pointearnevent",
                "ordering": ["-synced_at"],
            },
        ),
    ]
