# Generated by Django 6.0.7 on 2026-08-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointearnevent",
            name="source",
            field=models.CharField(
                choices=[("liftosaur", "Liftosaur"), ("manual", "Manual")],
                default="liftosaur",
                help_text="Provenance of the source LiftHistory set this event was scored from. PointEarnEvent has no FK to LiftHistory, so this is its own copy, not a derived lookup.",
                max_length=20,
            ),
        ),
    ]
