# Generated by Django 6.0.8 on 2026-08-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0004_alter_pointearnevent_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointearnevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("liftosaur", "Liftosaur"),
                    ("manual", "Manual"),
                    ("hevy", "Hevy"),
                    ("wger", "Wger"),
                    ("strong", "Strong"),
                ],
                default="liftosaur",
                help_text="Provenance of the source LiftHistory set this event was scored from. PointEarnEvent has no FK to LiftHistory, so this is its own copy, not a derived lookup.",
                max_length=20,
            ),
        ),
    ]
