# Generated by Django 6.0.8 on 2026-08-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0006_alter_pointearnevent_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointearnevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("liftosaur", "Liftosaur"),
                    ("liftosaur_csv", "Liftosaur (CSV import)"),
                    ("manual", "Manual"),
                    ("hevy", "Hevy"),
                    ("hevy_csv", "Hevy (CSV import)"),
                    ("wger", "Wger"),
                    ("strong_csv", "Strong (CSV import)"),
                ],
                default="liftosaur",
                help_text="Provenance of the source LiftHistory set this event was scored from. PointEarnEvent has no FK to LiftHistory, so this is its own copy, not a derived lookup.",
                max_length=20,
            ),
        ),
    ]
