# Generated by Django 6.0.7 on 2026-08-04 04:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FitnessVoltLiftAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_slug",
                    models.CharField(
                        help_text="Lift slug as FitnessVolt's /standards capability doc reports it.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "to_name",
                    models.CharField(
                        help_text="Canonical lift name used by the strength standards.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FitnessVolt lift aliases",
                "db_table": "fitnessvolt_liftalias",
                "ordering": ["from_slug"],
            },
        ),
        migrations.CreateModel(
            name="FitnessVoltStandardCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "population",
                    models.CharField(
                        choices=[
                            ("verified", "Verified (OpenPowerlifting SBD)"),
                            ("gym", "Gym (self-reported)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lift_slug",
                    models.CharField(
                        help_text="FitnessVolt's own lift slug, pre-mapping.",
                        max_length=100,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "weight_class_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight class in kg (unit=kg is requested at fetch time).",
                        max_digits=6,
                    ),
                ),
                (
                    "weight_class_label",
                    models.CharField(
                        help_text="FitnessVolt's own weight-class label, stored verbatim ('83 kg').",
                        max_length=50,
                    ),
                ),
                (
                    "percentiles",
                    models.JSONField(
                        help_text="Verbatim percentile -> 1RM kg table from the response, e.g. {'p10': 140, 'p25': 162.5, ..., 'p99': 270.5}."
                    ),
                ),
                ("sample_size", models.IntegerField()),
                (
                    "source_snapshot_version",
                    models.CharField(
                        help_text="Verbatim data_version from the response (e.g. '2026-06-09').",
                        max_length=100,
                    ),
                ),
                ("fetched_at", models.DateTimeField()),
            ],
            options={
                "db_table": "fitnessvolt_standardcache",
                "unique_together": {
                    (
                        "population",
                        "lift_slug",
                        "sex",
                        "weight_class_kg",
                        "source_snapshot_version",
                    )
                },
            },
        ),
    ]
