# Generated by Django 6.0.8 on 2026-08-25 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fitnessvolt", "0001_initial"),
        # Must run after the unified core.LiftAlias table has this app's
        # rows copied into it, or the delete loses data.
        ("core", "0006_copy_fitnessvolt_lift_aliases"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FitnessVoltLiftAlias",
        ),
    ]
