# Generated by Django 6.0.7 on 2026-08-04 04:51

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "history_window",
                    models.CharField(
                        choices=[
                            ("from_join", "From join date"),
                            ("from_start", "From challenge start"),
                        ],
                        default="from_join",
                        max_length=20,
                    ),
                ),
                (
                    "plate_unit",
                    models.CharField(
                        choices=[("lb", "Pounds (lb)"), ("kg", "Kilograms (kg)")],
                        default="lb",
                        max_length=2,
                    ),
                ),
                (
                    "smallest_plate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.25"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "challenges_challenge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeInviteLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_links",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_invite_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "challenges_challengeinvitelink",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeLift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_lifts",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_challengelift",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invite_status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("is_bailed", models.BooleanField(default=False)),
                ("bailed_at", models.DateTimeField(blank=True, null=True)),
                ("removed_by_creator", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "joined_via_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="joined_participants",
                        to="challenges.challengeinvitelink",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="challenge_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "challenges_challengeparticipant",
            },
        ),
        migrations.CreateModel(
            name="CustomGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "source_method",
                    models.CharField(
                        choices=[
                            ("standards", "Strength standards"),
                            ("history", "Suggested from history"),
                            ("custom", "Fully custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("source_detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_goals",
                        to="challenges.challengeparticipant",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_customgoal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="challengeparticipant",
            name="custom_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_for",
                to="challenges.customgoal",
            ),
        ),
        migrations.CreateModel(
            name="CustomGoalTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lift", models.CharField(max_length=100)),
                ("rep_count", models.PositiveSmallIntegerField()),
                ("target_weight", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="challenges.customgoal",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_customgoaltarget",
                "ordering": ["lift", "rep_count"],
            },
        ),
        migrations.AddConstraint(
            model_name="challengeinvitelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("challenge",),
                name="challengeinvitelink_one_live_per_challenge",
            ),
        ),
        migrations.AddConstraint(
            model_name="challengelift",
            constraint=models.UniqueConstraint(
                fields=("challenge", "name"),
                name="challengelift_unique_name_per_challenge",
            ),
        ),
        migrations.AddConstraint(
            model_name="customgoal",
            constraint=models.UniqueConstraint(
                fields=("participant", "name"),
                name="customgoal_unique_name_per_participant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="challengeparticipant",
            unique_together={("challenge", "user")},
        ),
        migrations.AddConstraint(
            model_name="customgoaltarget",
            constraint=models.UniqueConstraint(
                fields=("goal", "lift", "rep_count"),
                name="customgoaltarget_unique_lift_rep_per_goal",
            ),
        ),
        migrations.AddConstraint(
            model_name="customgoaltarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("rep_count__gte", 1), ("rep_count__lte", 10)),
                name="customgoaltarget_rep_count_1_to_10",
            ),
        ),
    ]
