# Generated by Django 6.0.8 on 2026-08-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_challengeinvitelink_max_uses_use_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customgoal",
            name="source_method",
            field=models.CharField(
                choices=[
                    ("standards", "Strength standards"),
                    ("history", "Suggested from history"),
                    ("custom", "Manual entry"),
                    ("json", "Paste JSON"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
    ]
