# Generated by Django 6.0.8 on 2026-08-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0003_alter_customgoal_source_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengeinvitelink",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
