# Generated by Django 6.0.8 on 2026-08-21 21:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0004_alter_challengeinvitelink_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="mode",
            field=models.CharField(
                choices=[("classic", "Classic"), ("rep_target", "Rep Target")],
                default="classic",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RepTargetGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "source_method",
                    models.CharField(
                        choices=[
                            ("history", "Suggested from history"),
                            ("custom", "Manual entry"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rep_target_goals",
                        to="challenges.challengeparticipant",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_reptargetgoal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="challengeparticipant",
            name="rep_target_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_for",
                to="challenges.reptargetgoal",
            ),
        ),
        migrations.CreateModel(
            name="RepTargetGoalTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lift", models.CharField(max_length=100)),
                ("target_weight", models.DecimalField(decimal_places=2, max_digits=7)),
                ("target_reps", models.PositiveSmallIntegerField()),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="challenges.reptargetgoal",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_reptargetgoaltarget",
                "ordering": ["lift"],
            },
        ),
        migrations.AddConstraint(
            model_name="reptargetgoal",
            constraint=models.UniqueConstraint(
                fields=("participant", "name"),
                name="reptargetgoal_unique_name_per_participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="reptargetgoaltarget",
            constraint=models.UniqueConstraint(
                fields=("goal", "lift"), name="reptargetgoaltarget_unique_lift_per_goal"
            ),
        ),
        migrations.AddConstraint(
            model_name="reptargetgoaltarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_reps__gte", 1), ("target_reps__lte", 999)),
                name="reptargetgoaltarget_target_reps_1_to_999",
            ),
        ),
    ]
