# Generated by Django 6.0.8 on 2026-09-02 02:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0005_challenge_mode_reptargetgoal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("joined", "Joined"),
                            ("left", "Left"),
                            ("removed", "Removed"),
                            ("ownership_transferred", "Ownership transferred"),
                            ("renamed", "Renamed"),
                            ("goal_locked", "Goal locked"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenge_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_challengeevent",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["challenge", "-created_at"],
                        name="challengeevent_log_idx",
                    )
                ],
            },
        ),
    ]
